-- Criação das sequências
CREATE SEQUENCE compra_seq START WITH 1 INCREMENT BY 50;
CREATE SEQUENCE item_compra_seq START WITH 1 INCREMENT BY 50;

-- Tabelas independentes (sem dependências de chaves estrangeiras)
CREATE TABLE organizador (
                             id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                             login VARCHAR(100) NOT NULL UNIQUE,
                             email VARCHAR(255) NOT NULL,
                             nome VARCHAR(255) NOT NULL,
                             senha VARCHAR(255) NOT NULL
);

CREATE TABLE cliente (
                         id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         login VARCHAR(100) NOT NULL UNIQUE,
                         email VARCHAR(255) NOT NULL,
                         nome VARCHAR(255) NOT NULL,
                         senha VARCHAR(255) NOT NULL
);

CREATE TABLE evento (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        capacidade_max INTEGER NOT NULL,
                        horario TIME(6) NOT NULL,
                        horario_fim TIME(6) NOT NULL,
                        descricao TEXT,
                        local VARCHAR(255) NOT NULL,
                        nome VARCHAR(255) NOT NULL
);

CREATE TABLE datas_evento (
                              id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                              data DATE NOT NULL
);

-- Tabelas que dependem de 'evento' e 'datas_evento'
CREATE TABLE evento_data_evento (
                                    datas_evento_id BIGINT NOT NULL,
                                    evento_id BIGINT NOT NULL,
                                    PRIMARY KEY (datas_evento_id, evento_id)
);

CREATE TABLE ingressos (
                           id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                           dias INTEGER NOT NULL,
                           evento_id BIGINT NOT NULL
);

-- Tabelas que dependem de 'ingressos'
CREATE TABLE modalidade (
                            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            ingressos_disponiveis INTEGER NOT NULL,
                            preco NUMERIC(38,2) NOT NULL,
                            ingresso_id BIGINT NOT NULL,
                            tipo_modalidade VARCHAR(255)
);

-- Tabelas que dependem de 'modalidade'
CREATE TABLE campo (
                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       modalidade_id BIGINT NOT NULL,
                       descricao_campo VARCHAR(255) NOT NULL,
                       nome_campo VARCHAR(255) NOT NULL
);

-- Tabelas que dependem de 'cliente' e 'evento'
CREATE TABLE compra (
                        id BIGINT PRIMARY KEY,
                        cliente_id BIGINT,
                        data_compra TIMESTAMP(6)
);

CREATE TABLE evento_organizador (
                                    evento_id BIGINT NOT NULL,
                                    organizador_id BIGINT NOT NULL,
                                    PRIMARY KEY (evento_id, organizador_id)
);

-- Tabelas que dependem de 'ingressos' e 'modalidade'
CREATE TABLE ingresso_comprado (
                                   id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                   cliente_id BIGINT NOT NULL,
                                   ingresso_id BIGINT NOT NULL,
                                   modalidade_id BIGINT NOT NULL
);

-- Tabelas que dependem de 'compra' e 'ingresso_comprado'
CREATE TABLE item_compra (
                             id BIGINT PRIMARY KEY,
                             compra_id BIGINT NOT NULL,
                             ingresso_id BIGINT NOT NULL,
                             modalidade_id BIGINT
);

-- Tabelas que dependem de 'campo' e 'ingresso_comprado'
CREATE TABLE resposta_campo (
                                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                campo_id BIGINT NOT NULL,
                                ingresso_comprado_id BIGINT NOT NULL,
                                resposta TEXT NOT NULL
);

-- Adição das chaves estrangeiras (agora que todas as tabelas estão criadas)
ALTER TABLE campo ADD CONSTRAINT fk_campo_modalidade FOREIGN KEY (modalidade_id) REFERENCES modalidade;
ALTER TABLE compra ADD CONSTRAINT fk_compra_cliente FOREIGN KEY (cliente_id) REFERENCES cliente;
ALTER TABLE evento_data_evento ADD CONSTRAINT fk_evento_data_evento_datas_evento FOREIGN KEY (datas_evento_id) REFERENCES datas_evento;
ALTER TABLE evento_data_evento ADD CONSTRAINT fk_evento_data_evento_evento FOREIGN KEY (evento_id) REFERENCES evento;
ALTER TABLE evento_organizador ADD CONSTRAINT fk_evento_organizador_organizador FOREIGN KEY (evento_id) REFERENCES organizador;
ALTER TABLE evento_organizador ADD CONSTRAINT fk_evento_organizador_evento FOREIGN KEY (organizador_id) REFERENCES evento;
ALTER TABLE ingresso_comprado ADD CONSTRAINT fk_ingresso_comprado_cliente FOREIGN KEY (cliente_id) REFERENCES cliente;
ALTER TABLE ingresso_comprado ADD CONSTRAINT fk_ingresso_comprado_ingressos FOREIGN KEY (ingresso_id) REFERENCES ingressos;
ALTER TABLE ingresso_comprado ADD CONSTRAINT fk_ingresso_comprado_modalidade FOREIGN KEY (modalidade_id) REFERENCES modalidade;
ALTER TABLE ingressos ADD CONSTRAINT fk_ingressos_evento FOREIGN KEY (evento_id) REFERENCES evento;
ALTER TABLE item_compra ADD CONSTRAINT fk_item_compra_compra FOREIGN KEY (compra_id) REFERENCES compra;
ALTER TABLE item_compra ADD CONSTRAINT fk_item_compra_ingresso_comprado FOREIGN KEY (ingresso_id) REFERENCES ingresso_comprado;
ALTER TABLE item_compra ADD CONSTRAINT fk_item_compra_modalidade FOREIGN KEY (modalidade_id) REFERENCES modalidade;
ALTER TABLE modalidade ADD CONSTRAINT fk_modalidade_ingressos FOREIGN KEY (ingresso_id) REFERENCES ingressos;
ALTER TABLE resposta_campo ADD CONSTRAINT fk_resposta_campo_campo FOREIGN KEY (campo_id) REFERENCES campo;
ALTER TABLE resposta_campo ADD CONSTRAINT fk_resposta_campo_ingresso_comprado FOREIGN KEY (ingresso_comprado_id) REFERENCES ingresso_comprado;